### PR TITLE
Add Rect3D and Rect2D and change Color to RGBA

### PR DESCRIPTION
**Pull request by NicEastvillage**

### CODE REVIEW

**Comment by NicEastvillage** [comment]
@VirxEC, do you know if I can give `Color.a` a default value of 255 without breaking anything?

**Comment by VirxEC** [comment]
However, changing the order of items in `Color` is a breaking change. Therefore this will result in RLBotServer v0.3

**Comment by NicEastvillage** [comment]
I'll let you handle the default value in `rlbot_flatbuffers_py`

**Comment by NicEastvillage** [comment]
It broke core :(
https://github.com/RLBot/core/actions/runs/11467640018/job/31910984806?pr=55

**Pull request merged**
